const RACE = [
	    '<h3>Humain</h3> 				<p><strong>Ajustement de caractéristique</strong>. +1 à toutes vos caractéristiques.</p> <p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 9 m par round.</p>	<p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et une langue supplémentaire de votre choix.</p>',
	    '<h3>Humain (option avec don)</h3><p><strong>Ajustement de caractéristique</strong>. +1 à deux caractéristiques différentes de votre choix.</p> <p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 9 m par round.</p>	<p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et une langue supplémentaire de votre choix.</p><p><strong>Compétences</strong>. Vous gagnez la maîtrise d\'une compétence de votre choix.</p><p><strong>Don</strong>. Vous obtenez un don de votre choix.</p>',
	    '<h3>Haut-elfe</h3>				<p><strong>Ajustement de caractéristique</strong>. Dextérité +2, Intelligence +1.</p> <p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 9 m par round.</p> <p><strong>Vision dans le noir</strong>.</p> <p><strong>Sens affûtés</strong>.</p> <p><strong>Héritage des fées</strong>.</p> <p><strong>Transe</strong>.</p> <p><strong>Armes elfes</strong>.</p> <p><strong>Sorts mineurs</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun, l\'elfique et une langue supplémentaire de votre choix.</p>',
	    '<h3>Elfe des bois</h3>			<p><strong>Ajustement de caractéristique</strong>. Dextérité +2, Sagesse +1.</p> <p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 10,50 m par round.</p> <p><strong>Vision dans le noir</strong>.</p> <p><strong>Sens affûtés</strong>.</p> <p><strong>Héritage des fées</strong>.</p>	<p><strong>Transe</strong>.</p>	<p><strong>Armes elfes</strong>.</p>	<p><strong>Camouflage de la nature</strong>.</p>	<p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et l\'elfique.</p>',
	    '<h3>Elfe noir</h3>				<p><strong>Ajustement de caractéristique</strong>. Dextérité +2, Charisme +1.</p> <p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 9 m par round.</p> <p><strong>Vision dans le noir supérieure</strong>.</p> <p><strong>Sens affûtés</strong>.</p> <p><strong>Héritage des fées</strong>.</p>	<p><strong>Transe</strong>.</p>	<p><strong>Armes drows</strong>.</p> <p><strong>Sensibilité à la lumière du soleil</strong>.</p> <p><strong>Magie drow</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et l\'elfique.</p>',
	    '<h3>Halfelin pied-léger</h3>	<p><strong>Ajustement de caractéristique</strong>. Dextérité +2, Charisme +1.</p> 	<p><strong>Taille</strong>. Petite (P).</p>	<p><strong>Vitesse</strong>. 7,50 m par round.</p> <p><strong>Chanceux</strong>.</p> <p><strong>Vaillant</strong>.</p> <p><strong>Agilité halfeline</strong>.</p> <p><strong>Discrétion naturelle</strong>.</p>	<p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et le halfelin.</p>',
	    '<h3>Halfelin corpulent</h3>	<p><strong>Ajustement de caractéristique</strong>. Dextérité +2, Constitution +1.</p> <p><strong>Taille</strong>. Petite (P).</p> <p><strong>Vitesse</strong>. 7,50 m par round.</p> <p><strong>Chanceux</strong>.</p> <p><strong>Vaillant</strong>.</p> <p><strong>Agilité halfeline</strong>.</p> <p><strong>Résistance du corpulent</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et le halfelin.</p>',
	    '<h3>Nain des collines</h3>		<p><strong>Ajustement de caractéristique</strong>. Constitution +2, Sagesse +1.</p>	<p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 7,50 m par round. Votre vitesse n\'est pas réduite par le port d\'une armure lourde.</p><p><strong>Vision dans le noir</strong>.</p> <p><strong>Résistance naine</strong>.</p> <p><strong>Armes naines</strong>.</p> <p><strong>Maîtrise des outils</strong>.</p> <p><strong>Connaissance de la pierre</strong>.</p> <p><strong>Robustesse naine</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et le nain.</p>',
	    '<h3>Nain des montagnes</h3>	<p><strong>Ajustement de caractéristique</strong>. Constitution +2, Force +2.</p> <p><strong>Taille</strong>. Moyenne (M).</p>	<p><strong>Vitesse</strong>. 7,50 m par round. Votre vitesse n\'est pas réduite par le port d\'une armure lourde.</p>	<p><strong>Vision dans le noir</strong>.</p> <p><strong>Résistance naine</strong>.</p> <p><strong>Armes naines</strong>.</p> <p><strong>Maîtrise des outils</strong>.</p> <p><strong>Connaissance de la pierre</strong>.</p> <p><strong>Entrainement aux armures</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et le nain.</p>',
	    '<h3>Gnome des forêts</h3>		<p><strong>Ajustement de caractéristique</strong>. Intelligence +2, Dextérité +1.</p> <p><strong>Taille</strong>. Petite (P).</p> <p><strong>Vitesse</strong>. 7,50 m par round.</p> <p><strong>Vision dans le noir</strong>.</p> <p><strong>Connaissance gnome</strong>.</p> <p><strong>Illusionniste naturel</strong>.</p> <p><strong>Parle avec les petits animaux</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et le gnome.</p>',
	    '<h3>Gnome des roches</h3>		<p><strong>Ajustement de caractéristique</strong>. Intelligence +2, Constitution +1.</p> <p><strong>Taille</strong>. Petite (P).</p> <p><strong>Vitesse</strong>. 7,50 m par round.</p> <p><strong>Vision dans le noir</strong>.</p> <p><strong>Connaissance gnome</strong>.</p> <p><strong>Ingénieur</strong>.</p> <p><strong>Bricoleur</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et le gnome.</p>',
	    '<h3>Demi-elfe</h3>				<p><strong>Ajustement de caractéristique</strong>. Charisme +2, +1 à deux autres caractéristiques de votre choix.</p> <p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 9 m par round.</p> <p><strong>Vision dans le noir</strong>.</p> <p><strong>Héritage des fées</strong>.</p> <p><strong>Versatilité</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun, l\'elfique et une langue supplémentaire de votre choix.</p>',
	    '<h3>Demi-orque</h3>			<p><strong>Ajustement de caractéristique</strong>. Force +2, Constitution +1.</p> <p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 9 m par round.</p> <p><strong>Vision dans le noir</strong>.</p> <p><strong>Menaçant</strong>.</p> <p><strong>Endurance tenace</strong>.</p> <p><strong>Attaques sauvages</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et l´orque.</p>',
	    '<h3>Drakéide</h3>				<p><strong>Ajustement de caractéristique</strong>. Force +2, Charisme +1.</p> <p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 9 m par round.</p> <p><strong>Ascendance draconique (Arme de souffle, Résistance aux dégâts)</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et le draconique.</p>',
	    '<h3>Tieffelin</h3>				<p><strong>Ajustement de caractéristique</strong>. Intelligence +1, Charisme +2.</p> <p><strong>Taille</strong>. Moyenne (M).</p> <p><strong>Vitesse</strong>. 9 m par round.</p> <p><strong>Vision dans le noir</strong>.</p> <p><strong>Résistance infernale</strong>.</p> <p><strong>Héritage infernal</strong>.</p> <p><strong>Langues</strong>. Vous pouvez parler, lire et écrire le commun et l´infernal.</p>'
];

const AGE = [
	    0, 20,  40,  60,  80,
	    0, 20,  40,  60,  80,
	    0, 25, 450, 650, 750,
	    0, 25, 450, 650, 750,
	    0, 25, 450, 650, 750,
	    0, 20,  70, 120, 150,
	    0, 20,  70, 120, 150,
	    0, 20, 150, 280, 350,
	    0, 20, 150, 280, 350,
	    0, 20, 220, 420, 500,
	    0, 20, 220, 420, 500,
	    0, 20, 100, 150, 180,
	    0, 15,  35,  55,  75,
	    0, 15,  45,  65,  80,
	    0, 20,  47,  74, 100
];

const CLASSE = [
	    '<h3>Barbare</h3>		<p><strong>DV</strong> : 1d12 par niveau de barbare</p><p><strong>Armures</strong> : armures légères et intermédiaires, boucliers</p><p><strong>Armes</strong> : armes courantes, armes de guerre</p><p><strong>Outils</strong> : aucun</p><p><strong>Jets de sauvegarde</strong> : Force, Constitution</p><p><strong>Compétences</strong> : choisissez deux compétences parmi Athlétisme, Dressage, Intimidation, Nature, Perception et Survie</p>',
	    '<h3>Barde</h3>			<p><strong>DV</strong> : 1d8 par niveau de barde</p><p><strong>Armures</strong> : armures légères</p><p><strong>Armes</strong> : armes courantes, arbalète légère, épée longue, épée courte, rapière</p><p><strong>Outils</strong> : trois instruments de musique de votre choix</p><p><strong>Jets de sauvegarde</strong> : Dextérité, Charisme</p><p><strong>Compétences</strong> : choisissez trois compétences de votre choix</p>',
	    '<h3>Clerc</h3>			<p><strong>DV</strong> : 1d8 par niveau de clerc</p><p><strong>Armures</strong> : armures légères et intermédiaires, boucliers</p><p><strong>Armes</strong> : armes courantes</p><p><strong>Outils</strong> : aucun</p><p><strong>Jets de sauvegarde</strong> : Sagesse, Charisme</p><p><strong>Compétences</strong> : choisissez deux compétences parmi Histoire, Intuition, Médecine, Persuasion et Religion</p>',
	    '<h3>Druide</h3>		<p><strong>DV</strong> : 1d8 par niveau de druide</p><p><strong>Armures</strong> : armures légères et intermédiaires, boucliers</p><p><strong>Armes</strong> : gourdin, dague, fléchette, javeline, masse d\'armes, bâton, cimeterre, fronde, serpe, lance</p><p><strong>Outils</strong> : kit d\'herboriste</p><p><strong>Jets de sauvegarde</strong> : Intelligence, Sagesse</p><p><strong>Compétences</strong> : choisissez deux compétences parmi Arcanes, Dressage, Intuition, Médecine, Nature, Perception, Religion et Survie</p>',
	    '<h3>Ensorceleur</h3>	<p><strong>DV</strong> : 1d6 par niveau d\'ensorceleur</p><p><strong>Armures</strong> : aucune</p><p><strong>Armes</strong> : dague, fléchette, fronde, bâton, arbalète légère</p><p><strong>Outils</strong> : aucun</p><p><strong>Jets de sauvegarde</strong> : Constitution, Charisme</p><p><strong>Compétences</strong> : choisissez deux compétences parmi Arcanes, Intimidation, Intuition, Persuasion, Religion et Tromperie</p>',
	    '<h3>Guerrier</h3>		<p><strong>DV</strong> : 1d10 par niveau de guerrier</p><p><strong>Armures</strong> : toutes les armures, boucliers</p><p><strong>Armes</strong> : armes courantes, armes de guerre</p><p><strong>Outils</strong> : aucun</p><p><strong>Jets de sauvegarde</strong> : Force, Constitution</p><p><strong>Compétences</strong> : choisissez deux compétences parmi Acrobaties, Athlétisme, Dressage, Histoire, Intimidation, Intuition, Perception et Survie</p>',
	    '<h3>Magicien</h3>		<p><strong>DV</strong> : 1d6 par niveau de magicien</p><p><strong>Armures</strong> : aucune</p><p><strong>Armes</strong> : dague, fléchette, fronde, bâton, arbalète légère</p><p><strong>Outils</strong> : aucun</p><p><strong>Jets de sauvegarde</strong> : Intelligence, Sagesse</p><p><strong>Compétences</strong> : choisissez deux compétences parmi Arcanes, Histoire, Intuition, Investigation, Médecine et Religion</p>',
	    '<h3>Moine</h3>			<p><strong>DV</strong> : 1d8 par niveau de moine</p><p><strong>Armures</strong> : aucune</p><p><strong>Armes</strong> : armes courantes, épée courte</p><p><strong>Outils</strong> : un outil d\'artisan ou un instrument de musique de votre choix</p><p><strong>Jets de sauvegarde</strong> : Force, Dextérité</p><p><strong>Compétences</strong> : choisissez deux compétences parmi Acrobaties, Athlétisme, Discrétion, Histoire, Intuition et Religion</p>',
	    '<h3>Paladin</h3>		<p><strong>DV</strong> : 1d10 par niveau de paladin</p><p><strong>Armures</strong> : toutes les armures, boucliers</p><p><strong>Armes</strong> : armes courantes, armes de guerre</p><p><strong>Outils</strong> : aucun</p><p><strong>Jets de sauvegarde</strong> : Sagesse, Charisme</p><p><strong>Compétences</strong> : choisissez deux compétences parmi Athlétisme, Intimidation, Intuition, Médecine, Persuasion et Religion</p>',
	    '<h3>Rôdeur</h3>		<p><strong>DV</strong> : 1d10 par niveau de rôdeur</p><p><strong>Armures</strong> : armures légères et intermédiaires, boucliers</p><p><strong>Armes</strong> : armes courantes, armes de guerre</p><p><strong>Outils</strong> : aucun</p><p><strong>Jets de sauvegarde</strong> : Force, Dextérité</p><p><strong>Compétences</strong> : choisissez trois compétences parmi Athlétisme, Discrétion, Dressage, Intuition, Investigation, Nature, Perception et Survie</p>',
	    '<h3>Roublard</h3>		<p><strong>DV</strong> : 1d8 par niveau de roublard</p><p><strong>Armures</strong> : armures légères</p><p><strong>Armes</strong> : armes courantes, arbalète de poing, épée courte, épée longue, rapière, arc court</p><p><strong>Outils</strong> : outils de voleur</p><p><strong>Jets de sauvegarde</strong> : Dextérité, Intelligence</p><p><strong>Compétences</strong> : choisissez quatre compétences parmi Acrobaties, Athlétisme, Discrétion, Escamotage, Intimidation, Intuition, Investigation, Perception, Persuasion, Représentation et Tromperie</p>',
	    '<h3>Sorcier</h3>		<p><strong>DV</strong> : 1d8 par niveau de sorcier</p><p><strong>Armures</strong> : armures légères</p><p><strong>Armes</strong> : armes courantes</p><p><strong>Outils</strong> : aucun</p><p><strong>Jets de sauvegarde</strong> : Sagesse, Charisme</p><p><strong>Compétences</strong> : choisissez deux compétences parmi Arcanes, Histoire, Intimidation, Investigation, Nature, Religion et Tromperie</p>'
];

const BACK = [
	    '<h3>Acolyte</h3>			<p><strong>Compétences maîtrisées</strong> : Intuition, Religion</p><p><strong>Langues</strong> : deux de votre choix</p><p><strong>Équipement</strong> : un symbole sacré (cadeau reçu lorsque vous êtes entré en sacerdoce), un livre de prière, 5 bâtons d\'encens, habit sacerdotal, des vêtements communs et une bourse contenant 15 po.</p><p><strong>Capacité</strong> : Abri du fidèle.<br />En tant qu\'acolyte, vous imposez le respect à ceux qui partagent votre foi, et pouvez mener les cérémonies religieuses de votre divinité. Vous et vos compagnons aventuriers pouvez vous attendre à recevoir des soins gratuits dans un temple, un sanctuaire ou toute autre présence établie de votre foi, bien que vous soyez responsable de fournir toutes les composantes matérielles nécessaires aux sorts. Ceux qui partagent votre religion vous aideront (mais seulement vous) et vous offriront un mode de vie modeste. Vous pouvez également avoir des liens avec un temple spécifique dédié à votre divinité ou votre panthéon, et vous y avez une résidence. Cela pourrait être le temple où vous avez servi, si vous êtes resté en bons termes avec lui, ou un temple dans lequel vous avez trouvé une nouvelle maison. Lorsque vous êtes proche de votre temple, vous pouvez faire appel à des religieux pour vous aider, à condition que l\'aide que vous demandiez ne soit pas dangereuse et que vous restiez en règle avec votre temple.</p>',
	    '<h3>Amuseur/Gladiateur</h3><p><strong>Compétences maîtrisées</strong> : Acrobaties, Représentation</p><p><strong>Outils maîtrisés</strong> : kit de déguisement, un type d\'instrument de musique</p><p><strong>Équipement</strong> : un instrument de musique (un de votre choix), un cadeau d\'un admirateur, un costume et une bourse contenant 15 po.</p><p><strong>Capacité</strong> : À la demande générale</p><br /><table><tr><td><strong>d10</strong></td><td><strong>Domaine</strong></td></tr><tr><td>1</td><td>Acteur</td></tr><tr><td>2</td><td>Danseur</td></tr><tr><td>3</td><td>Cracheur-de-feu</td></tr><tr><td>4</td><td>Bouffon</td></tr><tr><td>5</td><td>Jongleur</td></tr><tr><td>6</td><td>Musicien</td></tr><tr><td>7</td><td>Po&egrave;te</td></tr><tr><td>8</td><td>Chanteur</td></tr><tr><td>9</td><td>Conteur</td></tr><tr><td>10</td><td>Acrobate</td></tr></table>',
	    '<h3>Artisan de guilde/Commerçant de guilde</h3> <p><strong>Compétences maîtrisées</strong> : Intuition, Persuasion</p><p><strong>Outils maîtrisés</strong> : un type d\'outils d\'artisan</p><p><strong>Langues</strong> : une de votre choix</p><p><strong>Équipement</strong> : un jeu d\'outils d\'artisan (un de votre choix), une lettre de recommandation de votre guilde, des vêtements de voyage et une bourse contenant 15 po.</p><p><strong>Capacité</strong> : Membre de guilde</p><br /><table><tr><td><strong>d20</strong></td><td><strong>Affaires de la guilde</strong></td></tr><tr><td>1</td><td>Alchimistes et apothicaires</td></tr><tr><td>2</td><td>Armuriers, serruriers, orf&egrave;vres</td></tr><tr><td>3</td><td>Brasseurs, distillateurs, vignerons</td></tr><tr><td>4</td><td>Calligraphes, scribes, copistes</td></tr><tr><td>5</td><td>Cartographes, g&eacute;om&egrave;tres, architectes</td></tr><tr><td>6</td><td>Charrons</td></tr><tr><td>7</td><td>Charpentiers, couvreurs, pl&acirc;triers</td></tr><tr><td>8</td><td>Charpentiers de marine, fabricants de voile</td></tr><tr><td>9</td><td>Cuisiniers, boulangers</td></tr><tr><td>10</td><td>Forgerons</td></tr><tr><td>11</td><td>Joailliers, tailleurs de gemmes</td></tr><tr><td>12</td><td>Ma&ccedil;ons et tailleurs de pierres</td></tr><tr><td>13</td><td>Maroquiniers, peaussiers, tanneurs</td></tr><tr><td>14</td><td>Menuisiers, tonneliers, fabricants d\'arcs</td></tr><tr><td>15</td><td>Peintres, enlumineurs, fabricants d\'enseignes</td></tr><tr><td>16</td><td>Potiers et tuiliers</td></tr><tr><td>17</td><td>R&eacute;tameurs, faiseurs d\'&eacute;tain, fondeurs</td></tr><tr><td>18</td><td>Savetiers, cordonniers</td></tr><tr><td>19</td><td>Souffleurs de verre, vitriers</td></tr><tr><td>20</td><td>Tisserands et teinturiers</td></tr></table>',
	    '<h3>Charlatan</h3>			<p><strong>Compétences maîtrisées</strong> : Escamotage, Tromperie</p><p><strong>Outils maîtrisés</strong> : kit de contrefaçon, kit de déguisement</p><p><strong>Équipement</strong> : des vêtements fins, un kit de déguisement, des outils d\'escroquerie de votre choix (dés truqués, cartes marquées, fausse chevalière de duc, ...) et une bourse contenant 15 po.</p><p><strong>Capacité</strong> : Fausse identité</p>',
	    '<h3>Criminel/Espion</h3>	<p><strong>Compétences maîtrisées</strong> : Discrétion, Tromperie</p><p><strong>Outils maîtrisés</strong> : un type de jeu, outils de voleur</p><p><strong>Équipement</strong> : un pied de biche, des vêtements communs sombres avec une capuche et une bourse contenant 15 po.</p><p><strong>Capacité</strong> : Contact avec le crime</p><br /><table><tr><td><strong>d8</strong></td><td><strong>Sp&eacute;cialit&eacute;</strong></td></tr><tr><td>1</td><td>Ma&icirc;tre-chanteur</td></tr><tr><td>2</td><td>Cambrioleur</td></tr><tr><td>3</td><td>Homme de main</td></tr><tr><td>4</td><td>Receleur</td></tr><tr><td>5</td><td>Voleur de grand chemin</td></tr><tr><td>6</td><td>Tueur &agrave; gages</td></tr><tr><td>7</td><td>Pickpocket</td></tr><tr><td>8</td><td>Contrebandier</td></tr></table>',
	    '<h3>Ermite</h3>			<p><strong>Compétences maîtrisées</strong> : Médecine, Religion</p><p><strong>Langues</strong> : une de votre choix</p><p><strong>Outils maîtrisés</strong> : kit d\'herboriste</p><p><strong>Équipement</strong> : un étui à parchemin remplis de notes sur vos études ou vos prières, une couverture pour l\'hiver, des vêtements ordinaires, un kit d\'herboriste et 5 po.</p><p><strong>Capacité</strong> : Découverte</p>',
	    '<h3>Étranger</h3>			<p><strong>Compétences maîtrisées</strong> : Athlétisme, Survie</p><p><strong>Langues</strong> : une de votre choix</p><p><strong>Outils maîtrisés</strong> : un type d\'instrument de musique</p><p><strong>Équipement</strong> : un bâton, un piège de chasse, un trophée d\'animal que vous avez tué, des vêtements de voyage et une bourse contenant 10 po.</p><p><strong>Capacité</strong> : Voyageur</p><br /><table><tr><td><strong>d10</strong></td><td><strong>Origine</strong></td></tr><tr><td>1</td><td>Forestier</td></tr><tr><td>2</td><td>Trappeur</td></tr><tr><td>3</td><td>Colon</td></tr><tr><td>4</td><td>Guide</td></tr><tr><td>5</td><td>Exil&eacute; ou paria</td></tr><tr><td>6</td><td>Chasseur de prime</td></tr><tr><td>7</td><td>P&egrave;lerin</td></tr><tr><td>8</td><td>Nomade tribal</td></tr><tr><td>9</td><td>Chasseur</td></tr><tr><td>10</td><td>Pillard tribal</td></tr></table>',
	    '<h3>Gamin des rues</h3>	<p><strong>Compétences maîtrisées</strong> : Discrétion, Escamotage</p><p><strong>Outils maîtrisés</strong> : kit de déguisement, outils de voleur</p><p><strong>Équipement</strong> : un petit couteau, une carte de la ville où vous avez grandi, une souris, des vêtements communs et une bourse contenant 10 po.</p><p><strong>Capacité</strong> : Secrets de ville</p>',
	    '<h3>Héros du peuple</h3>	<p><strong>Compétences maîtrisées</strong> : Dressage, Survie</p><p><strong>Outils maîtrisés</strong> : un type d\'outils d\'artisan, véhicules (terrestre)</p><p><strong>Équipement</strong> : un jeu d\'outils d\'artisan (un de votre choix), une pelle, un pot en fer, des vêtements communs et une bourse contenant 10 po.</p><p><strong>Capacité</strong> : Hospitalité rurale</p>',
	    '<h3>Marin/Pirate</h3>		<p><strong>Compétences maîtrisées</strong> : Athlétisme, Perception</p><p><strong>Outils maîtrisés</strong> : outils de navigation, véhicules (maritime)</p><p><strong>Équipement</strong> : un cabillot d\'amarrage, corde en soie (15 m.), un porte bonheur (patte de lapin, petite pierre, ...), des vêtements communs et une bourse contenant 10 po.</p><p><strong>Capacité</strong> : Traversée en bateau</p>',
	    '<h3>Noble</h3>				<p><strong>Compétences maîtrisées</strong> : Histoire, Persuasion</p><p><strong>Langues</strong> : une de votre choix</p><p><strong>Outils maîtrisés</strong> : un type de jeu</p><p><strong>Équipement</strong> : des vêtements fins, une chevalière, un parchemin d\'ascendance et une bourse contenant 25 po.</p><p><strong>Capacité</strong> : Position de privilège</p>',
	    '<h3>Sage</h3>				<p><strong>Compétences maîtrisées</strong> : Arcanes, Histoire</p><p><strong>Langues</strong> : deux de votre choix</p><p><strong>Équipement</strong> : une bouteille d\'encre noire, une plume, un petit couteau, une lettre d\'un collègue mort posant une question à laquelle vous n\'avez pas encore été en mesure de répondre, des vêtements communs et une bourse contenant 10 po.</p><p><strong>Capacité</strong> : Chercheur</p><br /><table><tr><td><strong>d8</strong></td><td><strong>Sp&eacute;cialit&eacute;</strong></td></tr><tr><td>1</td><td>Alchimiste</td></tr><tr><td>2</td><td>Astronome</td></tr><tr><td>3</td><td>Acad&eacute;micien discr&eacute;dit&eacute;</td></tr><tr><td>4</td><td>Biblioth&eacute;caire</td></tr><tr><td>5</td><td>Professeur</td></tr><tr><td>6</td><td>Chercheur</td></tr><tr><td>7</td><td>Apprenti magicien</td></tr><tr><td>8</td><td>Scribe</td></tr></table>',
	    '<h3>Soldat</h3>			<p><strong>Compétences maîtrisées</strong> : Athlétisme, Intimidation</p><p><strong>Outils maîtrisés</strong> : un type de jeu, véhicules (terrestre)</p><p><strong>Équipement</strong> : une insigne de grade, un trophée pris sur un ennemi mort (une dague, une lame brisée, un morceau de bannière), un jeu de dés en os ou un jeu de cartes, des vêtements communs et une bourse contenant 10 po.</p><p><strong>Capacité</strong> : Grade</p><br /><table><tr><td><strong>d8</strong></td><td><strong>Sp&eacute;cialit&eacute;</strong></td></tr><tr><td>1</td><td>Officier</td></tr><tr><td>2</td><td>&Eacute;claireur</td></tr><tr><td>3</td><td>Infanterie</td></tr><tr><td>4</td><td>Cavalerie</td></tr><tr><td>5</td><td>Soigneur</td></tr><tr><td>6</td><td>Intendant</td></tr><tr><td>7</td><td>Porte-&eacute;tendard</td></tr><tr><td>8</td><td>Support (cuisine, forgeron, etc.)</td></tr></table>',
	    '<h3>Chevalier</h3>			<p><strong>Compétences maîtrisées</strong> : Histoire, Persuasion</p><p><strong>Langues</strong> : une de votre choix</p><p><strong>Outils maîtrisés</strong> : un type de jeu</p><p><strong>Équipement</strong> : des vêtements fins, une chevalière, un emblème et une bourse contenant 25 po.</p><p><strong>Capacité</strong> : Domestiques</p>',
	    '<h3>Voyageur</h3>			<p><strong>Compétences maîtrisées</strong> : Persuasion, Survie</p><p><strong>Langues</strong> : deux de votre choix</p><p><strong>Équipement</strong> : un bâton de marche, un souvenir venu d\'un pays lointain (choisir ou tirer sur la table des babioles), un livre rempli de notes sur vos périples ou de dessins, une fiole d\'encre et une plume, des vêtements de voyage et une sacoche contenant 10 po.</p><p><strong>Capacité</strong> : Couleur locale.<br />Vos voyages vous ont appris à adopter rapidement les coutumes des peuples que vous avez croisés, leur accent, leur façon de s\'habiller, de se comporter, jusqu\'à leur démarche. Lorsque vous arrivez dans une ville ou une région, il ne vous faut pas longtemps pour vous faire passer pour un local. De plus, vous pouvez, si vous le souhaitez, vous comporter comme si vous étiez originaire de tous les endroits que vous avez traversés. Au début de la partie, déterminez avec votre MD combien d\'origines vous pouvez imiter. Vous connaissez aussi quelques mots de nombreux langages, assez pour vous en sortir dans une interaction sociale de base (dire bonjour, merci, commander à boire par exemple) avec presque n\'importe quel humanoïde civilisé.</p><br /><table><tr><td><strong>d8</strong></td><td><strong>Mode de transport favori</strong></td></tr><tr><td>1</td><td>&Agrave; pied</td></tr><tr><td>2</td><td>&Agrave; cheval</td></tr><tr><td>3</td><td>Au sein d&rsquo;une caravane de marchands</td></tr><tr><td>4</td><td>En bateau</td></tr><tr><td>5</td><td>En charrette</td></tr><tr><td>6</td><td>Par des moyens magiques</td></tr><tr><td>7</td><td>En tant que passager clandestin</td></tr><tr><td>8</td><td>Aucun en particulier</td></tr></table><p><br /></p><p><em>Background non officiel élaboré par Lord Blackdeath (Gobelin d\'or 2015)</em></p>',
	    '<h3>Captif</h3>			<p><strong>Compétences maîtrisées</strong> : Nature, Survie</p><p><strong>Langues</strong> : la langue de la tribu de votre captivité</p><p><strong>Outils maîtrisés</strong> : un outil d\'artisan (en relation avec le travail que l\'on vous a forcé à faire)</p><p><strong>Équipement</strong> : des vêtements communs, un type d\'outils d\'artisan (ceux que vous aviez pour réaliser votre labeur), une bougie, une gamelle, une couverture et 5 po.</p><p><strong>Capacité</strong> : Connaisseur.<br />S\'il y a une chose de bénéfique que vous pouvez tirer de votre expérience, c\'est que vous avez vécu au contact de ces créatures un long moment, et avez pu apprendre de nombreuses choses sur leurs us et coutumes, le tout vu de l\'intérieur. Vous êtes donc maintenant un fin connaisseur de cette race. En plus de maitriser leur langue, vous connaissez leurs manières de vivre, leurs techniques de combat, leurs points forts et leurs points faibles.</p><br /><table><tr><td><strong>d8</strong></td><td><strong>Tribu (langue)</strong></td></tr><tr><td>1</td><td>Kobold (draconique)</td></tr><tr><td>2</td><td>Gobelin (gobelin)</td></tr><tr><td>3</td><td>Gnoll (gnoll)</td></tr><tr><td>4</td><td>Homme-l&eacute;zard (draconique)</td></tr><tr><td>5</td><td>Orque (orque)</td></tr><tr><td>6</td><td>Hobgobelin (gobelin)</td></tr><tr><td>7</td><td>Elfe noir (elfique ou commun des profondeurs)</td></tr><tr><td>8</td><td>Gobelours (gobelin)</td></tr></table><p><br /></p><p><em>Background non officiel élaboré par Blueace (Gobelin d\'argent 2015)</em></p>',
	    '<h3>Idiot du village</h3>	<p><strong>Compétences maîtrisées</strong> : Discrétion, Représentation</p><p><strong>Langues</strong> : vous parlez le gnééééé, une langue sans sens réel, basé sur des sons simples et des onomatopées.</p><p><strong>Outils maîtrisés</strong> : un type de jeu simple mais dont vous semblez être le seul à connaitre les règles.</p><p><strong>Équipement</strong> : un bâton, un sifflet, des vêtements rapiécés, une bourse contenant de jolis cailloux et un autre objet au choix (d\'une valeur maximale de 5 po).</p><p><strong>Capacité</strong> : Pitoyable.<br />Il est évident que vous êtes limité et que vous n\'êtes pas responsable de vos actes... Tout le monde s\'en rend compte dès le premier regard et cela vous permet d\'être traité différemment des personnes ordinaires. La plupart des gens font comme si vous n\'étiez pas là et vous pouvez donc trainer un peu partout sans attirer la méfiance. De plus, vous faites pitié et, en conséquence, le châtiment est toujours plus doux que le crime. Lorsque vous réalisez des actes répréhensibles ou vous trouvez à un endroit où vous ne devriez pas vous trouver, vous n\'êtes, la plupart du temps, pas inquiété : « c\'est pas sa faute, il est débile ! ». Mais cela ne vous empêche pas de prendre des coups de temps en temps lorsque vous vous faites virer.</p><p><br /></p><p><em>Background non officiel élaboré par Pouish (Gobelin de cuivre 2015)</em></p>',
	    '<h3>[Votre background]</h3><p>Si vous avez élaboré votre propre background, sélectionnez ce choix. Il ne remplira automatiquement aucun champ et vous laissera ainsi compléter les données de votre création à la main sur la fiche de personnage finale.</p>'
];

const INTRO = ['', '', '', 
	'<p>Les caractéristiques peuvent être déterminées de deux manières :</p><p>1) Répartition de 27 points suivant le barème des règles (max 15 pour une caractéristique). Le nombre de points consomés est indiqué en bas. Une répartition typique est :</p><h3>15 - 14 - 13 - 12 - 10 - 8</h3><p>ou</p><p>2) Tirez 6 fois 4d6, gardez les 3 meilleurs d6 à chaque fois, et reportez les scores dans l\'orde de votre choix. Votre tirage donne :</p>',
	'',
	'',
	'',
	'<p>Les points de vie (pv) peuvent être déterminés de deux manières :</p><p>1) pv max au niveau 1 puis moyenne arrondie au supérieur à chaque niveau suivant.</p><p>ou</p><p>2) pv max au niveau 1 puis lancez un DV à chaque niveau suivant.</p>',
	'',
	'<p>L\'équipement pré-sélectionné n\'est qu\'un exemple donné par les règles pour un niveau 1. Vous pouvez le modifier.</p><p>Consultez votre MD pour savoir combien de pièces d\'or vous pouvez dépenser suivant le niveau de votre personnage.</p>',
	'',
	'<p>* Capacité ou don pris en compte dans les calculs.</p><p><input type="button" class="bXport" value="Exporter" onclick="location=\'export.php\'" /></p><p>Exporter votre personnage dans un fichier au format .csv pour en faire une sauvegarde locale. Ceci vous permettra de reprendre plus tard votre fiche et de faire évoluer le personnage.</p><p><button class="bLang" value="" onclick="window.open(\'sheet.php\', \'_blank\')" >Finaliser</button></p><p>Remplir automatiquement la feuille de personnage D&D 5 officielle, prête pour l\'impression (n\'oubliez pas d\'activer l\'option \'Graphiques d\'arrière-plan\' depuis votre navigateur). Vous pouvez toutefois éditer manuellement les champs avant cela.</p><p><input type="button" class="bXport" value="BBcode" onclick="ClipBoard()" /></p><p>Ouvrir une fenêtre pop-up avec la fiche de personnage au format BBCode pour pouvoir la copier/coller directement sur le forum.</p>'
];

const STYLECOMBAT = [
	    '<h3>Archer</h3>				<p>Vous obtenez un bonus de +2 à l\'attaque avec une arme à distance.</p>',
	    '<h3>Défense</h3>				<p>Si vous portez une armure, vous obtenez un bonus de +1 à la CA.</p>',
	    '<h3>Duel</h3>					<p>Lorsque vous attaquez avec une arme de corps à corps dans une main et aucune autre arme, vous obtenez un bonus de +2 aux dégâts avec cette arme.</p>',
	    '<h3>Arme à deux mains</h3> 	<p>Lorsque vous obtenez 1 ou 2 à un dé de dégâts lors d\'une attaque que vous effectuez avec une arme de corps à corps que vous tenez avec vos deux mains, vous pouvez relancer le dé et obligatoirement prendre le nouveau résultat, même si celui-ci est un 1 ou un 2. L\'arme doit avoir la propriété à deux mains ou versatile pour octroyer cet avantage.</p>',
	    '<h3>Protection</h3>			<p>Quand une créature que vous pouvez voir attaque une cible autre que vous même et qui se trouve à 1,50 m ou moins de vous, vous pouvez utiliser votre réaction pour imposer un désavantage à son jet d\'attaque. Vous devez pour cela porter un bouclier.</p>',
	    '<h3>Combat à deux armes</h3>	<p>Lorsque vous vous engagez dans un combat avec deux armes en mains, vous pouvez ajouter votre modificateur de caractéristique aux dégâts de la seconde attaque.</p>'
];

const VOIEBAR = [
	    '<h3>Berserk</h3>				<ul><li>Niv 3 : Frénésie</li><li>Niv 6 : Rage inébranlable</li><li>Niv 10 : Présence intimidante</li><li>Niv 14 : Représailles</li></ul>',
	    '<h3>Guerrier totem</h3>		<ul><li>Niv 3 : Esprit chercheur, Esprit totem</li><li>Niv 6 : Aspect de la bête</li><li>Niv 10 : Communion avec la nature</li><li>Niv 14 : Lien totémique</li></ul>'
];

const VOIEBRD = [
	    '<h3>Connaissance</h3>			<ul><li>Niv 3 : Maîtrises additionnelles, Mots tranchants</li><li>Niv 6 : Secret magiques additionnels</li><li>Niv 14 : Compétences hors pair</li></ul>',
	    '<h3>Valeur</h3>				<ul><li>Niv 3 : Maîtrises additionnelles, Inspiration de combat</li><li>Niv 6 : Attaque supplémentaire</li><li>Niv 14 : Magie de bataille</li></ul>'
]; 

const VOIECLE = [
	    '<h3>Vie</h3>					<ul><li>Niv 1 : Sorts de domaine</li><ul><li>Niv 1 : <em>bénédiction, soins</em></li><li>Niv 3 : <em>arme spirituelle, restauration partielle</em></li><li>Niv 5 : <em>réanimation, signal d\'espérance</em></li><li>Niv 7 : <em>gardien de la foi, protection contre la mort</em></li><li>Niv 9 : <em>rappel à la vie, soins de groupe</em></li></ul><li>Niv 1 : Maîtrise additionnelle, Disciple de la vie</li><li>Niv 2 : Canalisation divine : préservation de vie</li><li>Niv 6 : Soigneur sacré</li><li>Niv 8 : Frappe divine</li><li>Niv 17 : Soins suprêmes</li></ul>',
	    '<h3>Guerre</h3>				<ul><li>Niv 1 : Sorts de domaine</li><ul><li>Niv 1 : <em>bouclier de la foi, faveur divine</em></li><li>Niv 3 : <em>arme magique, arme spirituelle</em></li><li>Niv 5 : <em>gardiens spirituels, manteau du croisé</em></li><li>Niv 7 : <em>liberté de mouvement, peau de pierre</em></li><li>Niv 9 : <em>colonne de feu, immobilisation de monstre</em></li></ul><li>Niv 1 : Maîtrises additionnelles, Prêtre de guerre</li><li>Niv 2 : Canalisation divine : coup au but</li><li>Niv 6 : Canalisation divine : bénédiction du dieu de la Guerre</li><li>Niv 8 : Frappe divine</li><li>Niv 17 : Avatar de bataille</li></ul>',
	    '<h3>Connaissance</h3>			<ul><li>Niv 1 : Sorts de domaine</li><ul><li>Niv 1 : <em>identification, injonction</em></li><li>Niv 3 : <em>augure, suggestion</em></li><li>Niv 5 : <em>antidétection, communication avec les morts</em></li><li>Niv 7 : <em>confusion, œil magique</em></li><li>Niv 9 : <em>mythes et légendes, scrutation</em></li></ul></li><li>Niv 1 : Bénédictions de la connaissance</li><li>Niv 2 : Canalisation divine : connaissance des âges</li><li>Niv 6 : Canalisation divine : lecture des pensées</li><li>Niv 8 : Incantation puissante</li><li>Niv 17 : Vision du passé</li></ul>',
	    '<h3>Duperie</h3>				<ul><li>Niv 1 : Sorts de domaine</li><ul><li>Niv 1 : <em>charme-personne, déguisement</em></li><li>Niv 3 : <em>image miroir, passage sans trace</em></li><li>Niv 5 : <em>clignotement, dissipation de la magie</em></li><li>Niv 7 : <em>métamorphose, porte dimensionnelle</em></li><li>Niv 9 : <em>domination, modificatino de la mémoire</em></li></ul></li><li>Niv 1 : Bénédiction du filou</li><li>Niv 2 : Canalisation divine : invocation de duplicité</li><li>Niv 6 : Canalisation divine : manteau d\'ombres</li><li>Niv 8 : Frappe divine</li><li>Niv 17 : Duplicité améliorée</li></ul>',
	    '<h3>Lumière</h3>				<ul><li>Niv 1 : Sorts de domaine</li><ul><li>Niv 1 : <em>lueur féerique, mains brûlantes</em></li><li>Niv 3 : <em>rayon ardent, sphère de feu</em></li><li>Niv 5 : <em>boule de feu, lumière du jour</em></li><li>Niv 7 : <em>gardien de la foi, mur de feu</em></li><li>Niv 9 : <em>colonne de feu, scrutation</em></li></ul></li><li>Niv 1 : Sort mineur bonus, Flamme gardienne</li><li>Niv 2 : Canalisation divine : radiance de l\'aube</li><li>Niv 6 : Flamme gardienne améliorée</li><li>Niv 8 : Incantation puissante</li><li>Niv 17 : Couronne de lumière</li></ul>',
	    '<h3>Nature</h3>				<ul><li>Niv 1 : Sorts de domaine</li><ul><li>Niv 1 : <em>amitié animale, compréhension animale</em></li><li>Niv 3 : <em>croissance d\'épines, peau d\'écorce</em></li><li>Niv 5 : <em>croissance végétale, mur de vent</em></li><li>Niv 7 : <em>domination de bête, lasso végétal</em></li><li>Niv 9 : <em>nuée d\'insectes, voyage par les arbres</em></li></ul></li><li>Niv 1 : Acolyte de la Nature, Maîtrise additionnelle</li><li>Niv 2 : Canalisation divine : charme des animaux et des plantes</li><li>Niv 6 : Affaiblissement des élements</li><li>Niv 8 : Frappe divine</li><li>Niv 17 : Maître de la Nature</li></ul>',
	    '<h3>Tempête</h3>				<ul><li>Niv 1 : Sorts de domaine</li><ul><li>Niv 1 : <em>nappe de brouillard, onde de choc</em></li><li>Niv 3 : <em>bourrasque, fracassement</em></li><li>Niv 5 : <em>appel de la foudre, giboulée</em></li><li>Niv 7 : <em>contrôle de l\'eau, tempête de grêle</em></li><li>Niv 9 : <em>nuée d\'insectes, vague destructrice</em></li></ul></li><li>Niv 1 : Maîtrises additionnelles, Colère de la Tempête</li><li>Niv 2 : Canalisation divine : colère destructrice</li><li>Niv 6 : Frappe de l\'éclair</li><li>Niv 8 : Frappe divine</li><li>Niv 17 : Fils de la tempête</li></ul>'
];

const VOIEDRU = [
	    '<h3>Cercle de la terre</h3>	<ul><li>Niv 2 : Sort mineur supplémentaire, Récupération naturelle, Sorts de cercle</li><li>Niv 6 : Traversée des terrains</li><li>Niv 10 : Protection de la nature</li><li>Niv 14 : Sanctuaire de la nature</li></ul>',
	    '<h3>Cercle de la lune</h3>		<ul><li>Niv 2 : Combat sous forme animale, Formes de cercle</li><li>Niv 6 : Attaque bestiale</li><li>Niv 10 : Forme élémentaire</li><li>Niv 14 : Milles formes</li></ul>'
];

const VOIEENS = [
	    '<h3>Lignée draconique</h3>		<ul><li>Niv 1 : Ancêtre dragon, Résilience draconique</li><li>Niv 6 : Affinité élémentaire</li><li>Niv 14 : Ailes de dragon</li><li>Niv 18 : Présence draconique</li></ul>',
	    '<h3>Magie sauvage</h3>			<ul><li>Niv 1 : Sursaut de magie sauvage, Vague de chaos</li><li>Niv 6 : Chance altérée</li><li>Niv 14 : Chaos contrôlé</li><li>Niv 18 : Bombardement de sort</li></ul>'
];

const VOIEGUE = [
	    '<h3>Champion</h3>				<ul><li>Niv 3 : Critique amélioré</li><li>Niv 7 : Athlète remarquable</li><li>Niv 10 : Nouveau style de combat</li><li>Niv 15 : Critique supérieur</li><li>Niv 18 : Survivant</li></ul>',
	    '<h3>Maître d\'armes</h3>		<ul><li>Niv 3 : Étudiant de guerre, Supériorité au combat</li><li>Niv 7 : Connaître son ennemi</li><li>Niv 10 : Supériorité au combat améliorée</li><li>Niv 15 : Implacable</li></ul>',
	    '<h3>Chevalier occultiste</h3>	<ul><li>Niv 3 : Sorts, Lien martial</li><li>Niv 7 : Magie de guerre</li><li>Niv 10 : Frappe occultiste</li><li>Niv 15 : Charge arcanique</li><li>Niv 18 : Magie de guerre améliorée</li></ul>'
];

const VOIEMAG = [
	    '<h3>École d\'évocation</h3>		<p>Les sorts d\'évocation manipulent l\'énergie magique jusqu\'à produire l\'effet désiré. Certaines évoquent des explosions de feu ou de foudre. D\'autres canalisent l\'énergie positive afin de guérir les blessures.</p><ul><li>Niv 2 : Savant évocateur, Sorts façonnés</li><li>Niv 6 : Sort mineur puissant</li><li>Niv 10 : Évocation améliorée</li><li>Niv 14 : Maître de l\'évocation</li></ul>',
	    '<h3>École d\'illusion</h3>		<p>Les sorts d\'illusion trompent les sens ou l\'esprit des autres. Ils amènent les gens à percevoir des choses qui ne sont pas là, à manquer des choses qui sont là, à entendre des bruits fantômes, ou à se souvenir de choses qui n\'ont jamais eu lieu. Certaines illusions créent des images fantômes que les créatures peuvent voir, mais les illusions les plus insidieuses sont les illusions qui implantent directement une image dans l\'esprit d\'une créature.</p><ul><li>Niv 2 : Savant illusionniste, Illusion mineure améliorée</li><li>Niv 6 : Illusions malléables</li><li>Niv 10 : Double illusoire</li><li>Niv 14 : Réalité illusoire</li></ul>',
	    '<h3>École d\'abjuration</h3>	<p>Les sorts d\'abjuration sont en règle générale des sorts de protection, même si certains d\'entre eux ont des utilisations agressives. Ils créent des barrières magiques, annulent des effets nocifs, endommagent les intrus, ou bannissent des créatures sur un autre plan d\'existence.</p><ul><li>Niv 2 : Savant abjurateur, Sceau arcanique</li><li>Niv 6 : Protection projetée</li><li>Niv 10 : Abjuration améliorée</li><li>Niv 14 : Résistance contre les sorts</li></ul>',
	    '<h3>École de divination</h3>	<p>Les sorts de divination révèlent des informations, que ce soit sous la forme de secrets oubliés depuis longtemps, d\'aperçus du futur, d\'emplacements de choses cachées, de vérité derrière les illusions, ou de visions de personnes ou de lieux éloignées.</p><ul><li>Niv 2 : Savant devin, Présage</li><li>Niv 6 : Expert en divination</li><li>Niv 10 : Troisième oeil</li><li>Niv 14 : Grand présage</li></ul>',
	    '<h3>École d\'enchantement</h3>	<p>Les sorts d\'enchantement affectent l\'esprit des autres, en influençant ou en contrôlant leur comportement. Ces sorts peuvent faire en sorte que les ennemis perçoivent le lanceur de sorts comme un ami, forcer des créatures à prendre une action, ou même contrôler une autre créature comme une marionnette.</p><ul><li>Niv 2 : Savant enchanteur, Regard hypnotique</li><li>Niv 6 : Charme instinctif</li><li>Niv 10 : Enchantement divisé</li><li>Niv 14 : Altération de la mémoire</li></ul>',
	    '<h3>École d\'invocation</h3>	<p>Les sorts d\'invocation touchent au transport d\'objets et des créatures d\'un endroit à un autre. Certains sorts invoquent des créatures ou des objets aux côtés du lanceur de sorts, alors que d\'autres permettent au lanceur de sorts de se téléporter vers un autre lieu. Certaines invocations créent des objets ou des effets à partir de rien.</p><ul><li>Niv 2 : Savant invocateur, Invocation mineure</li><li>Niv 6 : Transposition</li><li>Niv 10 : Invocation focalisée</li><li>Niv 14 : Convocations résistantes</li></ul>',
	    '<h3>École de nécromancie</h3>	<p>Les sorts de nécromancie manipulent les énergies de la vie et de la mort. Certains sorts peuvent accorder une réserve supplémentaire de force de vie, drainer l\'énergie de la vie d\'une autre créature, créer des morts-vivants, ou même ramener les morts à la vie. La création de morts-vivants grâce à l\'utilisation de sorts de nécromancie comme <em>animation de mort</em>, n\'est pas un acte de nature bonne, et seuls les lanceurs de sorts mauvais utilisent ces sorts fréquemment.</p><ul><li>Niv 2 : Savant nécromant, Sombre récolte</li><li>Niv 6 : Servitude de morts-vivants</li><li>Niv 10 : Résistance à la non-vie</li><li>Niv 14 : Contrôle des morts-vivants</li></ul>',
	    '<h3>École de transmutation</h3><p>Les sorts de transmutation modifient les propriétés d\'une créature, d\'un objet ou d\'un environnement. Ils peuvent transformer un ennemi en une créature inoffensive, améliorer la force d\'un allié, faire qu\'un objet puisse se déplacer sur commande du lanceur de sorts, ou augmenter les capacités innées de guérison d\'une créature afin qu\'elle puisse récupérer plus rapidement d\'une blessure.</p><ul><li>Niv 2 : Savant transmutateur, Alchimie mineure</li><li>Niv 6 : Pierre du transmutateur</li><li>Niv 10 : Métamorphe</li><li>Niv 14 : Maître transmutateur</li></ul>'
];

const VOIEMOI = [
	    '<h3>Voie de la paume</h3>			<ul><li>Niv 3 : Technique de la paume</li><li>Niv 6 : Intégrité physique</li><li>Niv 11 : Tranquilité</li><li>Niv 17 : Paume frémissante</li></ul>',
	    '<h3>Voie des quatre éléments</h3>	<ul><li>Niv 3 : Disciple des élements</li><li>Niv 6 : Techniques élémentaires</li><li>Niv 11 : Techniques élémentaires</li><li>Niv 17 : Techniques élémentaires</li></ul>',
	    '<h3>Voie de l\'ombre</h3>			<ul><li>Niv 3 : Arts des ombres</li><li>Niv 6 : Passage par les ombres</li><li>Niv 11 : Voile d\'ombres</li><li>Niv 17 : Opportuniste</li></ul>'
];

const VOIEPAL = [
	    '<h3>Serment de Dévotion</h3>	<ul><li>Niv 1 : Sorts de serment</li><li>Niv 3 : Canalisation divine (arme sacrée), Canalisation divine (renvoi des impies)</li><li>Niv 7 : Aura de dévotion</li><li>Niv 15 : Pureté de l\'esprit</li><li>Niv 20 : Halo sacré</li></ul>',
	    '<h3>Serment des Anciens</h3>	<ul><li>Niv 1 : Sorts de serment</li><li>Niv 3 : Canalisation divine (colère de la nature), Canalisation divine (renvoi des infidèles)</li><li>Niv 7 : Aura de garde</li><li>Niv 15 : Sentinelle immortelle</li><li>Niv 20 : Champion des Anciens</li></ul>',
	    '<h3>Serment de Vengeance</h3>	<ul><li>Niv 1 : Sorts de serment</li><li>Niv 3 : Canalisation divine (abjure l\'ennemi), Canalisation divine (voeu d\'inimité)</li><li>Niv 7 : Vengeur implacable</li><li>Niv 15 : Âme de vengeance</li><li>Niv 20 : Ange vengeur</li></ul>'
];

const VOIEROD = [
	    '<h3>Chasseur</h3>		  <ul><li>Niv 3 : Proie du chasseur</li><li>Niv 7 : Tactiques défensives</li><li>Niv 11 : Attaques multiples</li><li>Niv 15 : Défense du chasseur supérieure</li></ul>',
	    '<h3>Maître des bêtes</h3><ul><li>Niv 3 : Compagnon animal</li><li>Niv 7 : Entraînement exceptionnel</li><li>Niv 11 : Furie bestiale</li><li>Niv 15 : Partage de sorts</li></ul>'
];

const VOIEROU = [
	    '<h3>Voleur</h3>				<ul><li>Niv 3 : Cambriolage, Mains rapides</li><li>Niv 9 : Discrétion suprême</li><li>Niv 13 : Utiliser des objets magiques</li><li>Niv 16 : Réflexes de voleur</li></ul>',
	    '<h3>Assassin</h3>				<ul><li>Niv 3 : Assassin, Maîtrises additionnelles</li><li>Niv 9 : Expert en infiltration</li><li>Niv 13 : Imposteur</li><li>Niv 16 : Coup mortel</li></ul>',
	    '<h3>Mystificateur profane</h3>	<ul><li>Niv 3 : Sorts, Manipulation à distance</li><li>Niv 9 : Embuscade magique</li><li>Niv 13 : Filou versatile</li><li>Niv 16 : Voleur de sort</li></ul>'
];

const VOIESOR = [
	    '<h3>Fiélon</h3>				<ul><li>Niv 1 : Liste de sorts étendue</li><li>Niv 1 : Bénédiction de l\'Obscur</li><li>Niv 6 : Chance de l\'Obscur</li><li>Niv 10 : Résistance du fiélon</li><li>Niv 14 : Jeté aux enfers</li></ul>',
	    '<h3>Archi-fée</h3>				<ul><li>Niv 1 : Liste de sorts étendue</li><li>Niv 1 : Présence féerique</li><li>Niv 6 : Disparition brumeuse</li><li>Niv 10 : Défenses séduisantes</li><li>Niv 14 : Sombre délirium</li></ul>',
	    '<h3>Grand Ancien</h3>			<ul><li>Niv 1 : Liste de sorts étendue</li><li>Niv 1 : Esprit éveillée</li><li>Niv 6 : Protection entropique</li><li>Niv 10 : Bouclier des pensées</li><li>Niv 14 : Servitude</li></ul>'
];

const PREREQUIS = [
	    '', '', '', '', '', '', '<h3>Duelliste défensif</h3><p>Pré-requis : 13 ou plus en Dextérité</p>', '', '', '',
	    '<h3>Adepte élémentaire</h3><p>Pré-requis : Capacité de lancer au moins un sort</p>', '<h3>Lutteur</h3><p>Pré-requis : 13 ou plus en Force</p>', '', '', '<h3>Amateur d\'armures lourdes</h3><p>Pré-requis : Maîtrise des armures intermédiaires</p>', '<h3>Maître des armures lourdes</h3><p>Pré-requis : Maîtrise des armures lourdes</p>', '<h3>Leader inspirant</h3><p>Pré-requis : 13 ou plus en Charisme</p>', '', '', '',
	    '', '', '', '', '<h3>Maître des armures intermédiaires</h3><p>Pré-requis : Maîtrise des armures intermédiaires</p>', '', '<h3>Amateur d\'armures intermédiaires</h3><p>Pré-requis : Maîtrise des armures légères</p>', '', '', '',
	    '', '<h3>Lanceur de rituels</h3><p>Pré-requis : 13 ou plus en Intelligence ou Sagesse</p>', '', '', '', '', '', '<h3>Furtif</h3><p>Pré-requis : 13 ou plus en Dextérité</p>', '<h3>Lanceur de sorts d\'attaque</h3><p>Pré-requis : Capacité de lancer au moins un sort</p>', '',
	    '', '<h3>Lanceur de sorts de batailles</h3><p>Pré-requis : Capacité de lancer au moins un sort</p>', ''
];

const PACK = [ '<p>Pack (a) de barbare :</p><ul><li>Grande hache</li><li>2 haches</li><li>4 javelines</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (b) de barbare :</p><ul><li>Arme de guerre de corps à corps</li><li>Arme courante</li><li>4 javelines</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (a) de barde :</p><ul><li>Armure de cuir</li><li>Rapière</li><li>Dague</li><li>Luth</li><li>Sac de diplomate</li></ul>',
			 '<p>Pack (b) de barde :</p><ul><li>Armure de cuir</li><li>Épée longue</li><li>Dague</li><li>Instrument de musique</li><li>Sac d\'amuseur</li></ul>',
			 '<p>Pack (a) de clerc :</p><ul><li>Armure d\'écailles</li><li>Bouclier</li><li>Masse d\'armes</li><li>Arbalète légère</li><li>Symbole sacré</li><li>Sac de religieux</li></ul>',
			 '<p>Pack (b) de clerc :</p><ul><li>Armure de cuir</li><li>Bouclier</li><li>Marteau de guerre</li><li>Arme courante</li><li>Symbole sacré</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (a) de druide :</p><ul><li>Armure de cuir</li><li>Bouclier</li><li>Cimeterre</li><li>Focaliseur druidique</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (b) de druide :</p><ul><li>Armure de cuir</li><li>Arme courante</li><li>Arme courante de corps à corps</li><li>Focaliseur druidique</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (a) d\'ensorceleur :</p><ul><li>Arbalète légère et 20 carreaux</li><li>2 dagues</li><li>Sacoche à composants</li><li>Sac de donjoneur</li></ul>',
			 '<p>Pack (b) d\'ensorceleur :</p><ul><li>Arme courante</li><li>2 dagues</li><li>Focaliseur arcanique</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (a) de guerrier :</p><ul><li>Cotte de mailles</li><li>Bouclier</li><li>Arme de guerre</li><li>Arbalète légère</li><li>Sac de donjoneur</li></ul>',
			 '<p>Pack (b) de guerrier :</p><ul><li>Armure de cuir</li><li>2 armes de guerre</li><li>2 haches</li><li>Arc long</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (a) de magicien :</p><ul><li>Bâton</li><li>Grimoire</li><li>Sacoche à composantes</li><li>Sac d\'érudit</li></ul>',
			 '<p>Pack (b) de magicien :</p><ul><li>Dague</li><li>Grimoire</li><li>Focaliseur arcanique</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (a) de moine :</p><ul><li>Épée courte</li><li>10 fléchettes</li><li>Sac de donjoneur</li></ul>',
			 '<p>Pack (b) de moine :</p><ul><li>Arme courante</li><li>10 fléchettes</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (a) de paladin :</p><ul><li>Cotte de mailles</li><li>Bouclier</li><li>Arme de guerre</li><li>5 javelines</li><li>Symbole sacré</li><li>Sac de religieux</li></ul>',
			 '<p>Pack (b) de paladin :</p><ul><li>Cotte de mailles</li><li>2 armes de guerre</li><li>Arme courante de corps à corps</li><li>Symbole sacré</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (a) de rôdeur :</p><ul><li>Armure d\'écailles</li><li>2 épées courtes</li><li>Arc long</li><li>Sac de donjoneur</li></ul>',
			 '<p>Pack (b) de rôdeur :</p><ul><li>Armure de cuir</li><li>2 armes courantes de corps à corps</li><li>Arc long</li><li>Sac d\'explorateur</li></ul>',
			 '<p>Pack (a) de roublard :</p><ul><li>Armure de cuir</li><li>Rapière</li><li>Arc court</li><li>2 dagues</li><li>Outils de voleur</li><li>Sac de cambrioleur</li></ul>',
			 '<p>Pack (b) de roublard :</p><ul><li>Armure de cuir</li><li>2 épées courtes</li><li>2 dagues</li><li>Outils de voleur</li><li>Sac de donjoneur</li></ul>',
			 '<p>Pack (a) de sorcier :</p><ul><li>Armure de cuir</li><li>2 dagues</li><li>Arbalète légère et 20 carreaux</li><li>Arme courante</li><li>Sacoche à composants</li><li>Sac d\'érudit</li></ul>',
			 '<p>Pack (b) de sorcier :</p><ul><li>Armure de cuir</li><li>2 dagues</li><li>2 armes courantes</li></li><li>Focaliseur arcanique</li><li>Sac de donjoneur</li></ul>'
];

const ARMURE = [' ',
	'<h3>Armure matelassée</h3>		<p>Armure légère (4 kg.)<br />CA : 11 + modificateur de Dextérité<br />Désavantage en discrétion</p>',
	'<h3>Armure de cuir</h3> 		<p>Armure légère (5 kg.)<br />CA : 11 + modificateur de Dextérité</p>',				
	'<h3>Armure de cuir cloutée</h3><p>Armure légère (6,5 kg.)<br />CA : 12 + modificateur de Dextérité</p>',				
	'<h3>Armure de peau</h3> 		<p>Armure intermédiaire (6 kg.)<br />CA : 12 + modificateur de Dextérité (max 2)</p>',			 
	'<h3>Chemisse de mailles</h3> 	<p>Armure intermédiaire (10 kg.)<br />CA : 13 + modificateur de Dextérité (max 2)</p>',				 
	'<h3>Armure d\'écailles</h3> 	<p>Armure intermédiaire (22 kg.)<br />CA : 14 + modificateur de Dextérité (max 2)<br />Désavantage en discrétion</p>',	
	'<h3>Cuirasse</h3>				<p>Armure intermédiaire (10 kg.)<br />CA : 14 + modificateur de Dextérité (max 2)</p>',	
	'<h3>Armure à plaques</h3> 		<p>Armure intermédiaire (20 kg.)<br />CA : 15 + modificateur de Dextérité (max 2)<br />Désavantage en discrétion</p>', 	

	'<h3>Broigne</h3> 				<p>Armure lourde (20 kg.)<br />CA : 14<br />Désavantage en discrétion</p>', 	 
	'<h3>Cotte de mailles</h3> 		<p>Armure lourde (27 kg.)<br />CA : 16<br />Désavantage en discrétion<br />Vitesse -3 m si Force < 13</p>', 	
	'<h3>Clibanion</h3> 			<p>Armure lourde (30 kg.)<br />CA : 17<br />Désavantage en discrétion<br />Vitesse -3 m si Force < 15</p>', 	   	 	
	'<h3>Harnois</h3> 				<p>Armure lourde (32 kg.)<br />CA : 18<br />Désavantage en discrétion<br />Vitesse -3 m si Force < 15</p>'
];

const BOUCLIER = [ ' ',
	'<h3>Bouclier</h3> 				<p>Bouclier (3 kg.)<br />CA : +2</p>'
];

const ARME = [ ' ',
	'<h3>Mains nues</h3>',
	'<h3>Bâton</h3> 				<p>Arme courante de corps à corps (2 kg.) <br />Dégâts : 1d6 (contondant)<br />Versatile (1d8)</p>',
	'<h3>Dague</h3> 				<p>Arme courante de corps à corps (500 g.)<br />Dégâts : 1d4 (perforant)<br />Finesse, légère, lancer (portée 6/18)</p>',
	'<h3>Gourdin</h3> 				<p>Arme courante de corps à corps (1 kg.) <br />Dégâts : 1d4 (contondant)<br />Légère</p>',
	'<h3>Hache</h3> 				<p>Arme courante de corps à corps (1 kg.) <br />Dégâts : 1d6 (tranchant)<br />Légère, lancer (portée 6/18)</p>',
	'<h3>Javeline</h3> 				<p>Arme courante de corps à corps (1 kg.) <br />Dégâts : 1d6 (perforant)<br />Lancer (portée 9/36)</p>',
	'<h3>Lance</h3> 				<p>Arme courante de corps à corps (1,5 kg.) <br />Dégâts : 1d6 (perforant)<br />Lancer (portée 6/18), versatile (1d8)</p>',
	'<h3>Marteau léger</h3> 		<p>Arme courante de corps à corps (1 kg.) <br />Dégâts : 1d4 (contondant)<br />Légère, lancer (portée 6/18)</p>',
	'<h3>Masse d\'armes</h3> 		<p>Arme courante de corps à corps (2 kg.) <br />Dégâts : 1d6 (contondant)</p>',
	'<h3>Massue</h3> 				<p>Arme courante de corps à corps (5 kg.) <br />Dégâts : 1d8 (contondant)<br />À deux mains</p>',
	'<h3>Serpe</h3> 				<p>Arme courante de corps à corps (1 kg.) <br />Dégâts : 1d4 (tranchant)<br />Légère</p>',

	'<h3>Arbalète légère</h3> 		<p>Arme courante à distance (2,5 kg.) <br />Dégâts : 1d8 (perforant)<br />Munitions (portée 24/96), chargement, à deux mains</p>',
	'<h3>Arc court</h3> 			<p>Arme courante à distance (1 kg.) <br />Dégâts : 1d6 (perforant)<br />Munitions (portée 24/96), à deux mains</p>',
	'<h3>Fléchette</h3> 			<p>Arme courante à distance (100 g.)<br />Dégâts : 1d4 (perforant)<br />Finesse, lancer (portée 9/36)</p>',
	'<h3>Fronde</h3> 				<p>Arme courante à distance<br />Dégâts : 1d4 (contondant)<br />Munitions (portée 9/36)</p>',

	'<h3>Cimeterre</h3> 			<p>Arme de guerre de corps à corps (1,5 kg.)<br />Dégâts : 1d6 (tranchant)<br />Finesse, légère</p>',
	'<h3>Coutille</h3> 				<p>Arme de guerre de corps à corps (3 kg.)<br />Dégâts : 1d10 (tranchant)<br />Lourde, allonge, à deux mains</p>',
	'<h3>Épée à deux mains</h3>		<p>Arme de guerre de corps à corps (3 kg.)<br />Dégâts : 2d6 (tranchant)<br />Lourde, à deux mains</p>',
	'<h3>Épée courte</h3> 			<p>Arme de guerre de corps à corps (1 kg.)<br />Dégâts : 1d6 (perforant)<br />Finesse, légère</p>',
	'<h3>Épée longue</h3> 			<p>Arme de guerre de corps à corps (1,5 kg.)<br />Dégâts : 1d8 (tranchant)<br />Versatile (1d10)</p>',
	'<h3>Fléau d\'armes</h3> 		<p>Arme de guerre de corps à corps (1 kg.)<br />Dégâts : 1d8 (contondant)</p>',
	'<h3>Fouet</h3> 				<p>Arme de guerre de corps à corps (1,5 kg.)<br />Dégâts : 1d4 (tranchant<br />Finesse, allonge</p>',
	'<h3>Grande hache</h3> 			<p>Arme de guerre de corps à corps (3,5 kg.)<br />Dégâts : 1d12 (tranchant)<br />Lourde, à deux mains</p>',
	'<h3>Hache d\'armes</h3> 		<p>Arme de guerre de corps à corps (2 kg.)<br />Dégâts : 1d8 (tranchant)<br />Versatile (1d10)</p>',
	'<h3>Hallebarde</h3> 			<p>Arme de guerre de corps à corps (3 kg.)<br />Dégâts : 1d10 (tranchant)<br />Lourde, allonge, à deux mains</p>',

	'<h3>Lance d\'arçon</h3> 		<p>Arme de guerre de corps à corps (3 kg.)<br />Dégâts : 1d12 (perforant)<br />Allonge, spécial</p>',
	'<h3>Maillet</h3> 				<p>Arme de guerre de corps à corps (5 kg.)<br />Dégâts : 2d6 (contondant)<br />Lourde, à deux mains</p>',
	'<h3>Marteau de guerre</h3>		<p>Arme de guerre de corps à corps (1 kg.)<br />Dégâts : 1d8 (contondant)<br />Versatile (1d10)</p>',
	'<h3>Morgenstern</h3> 			<p>Arme de guerre de corps à corps (2 kg.)<br />Dégâts : 1d8 (perforant)</p>',
	'<h3>Pic de guerre</h3> 		<p>Arme de guerre de corps à corps (1 kg.)<br />Dégâts : 1d8 (perforant)</p>',
	'<h3>Pique</h3> 				<p>Arme de guerre de corps à corps (9 kg.)<br />Dégâts : 1d10 (perforant)<br />Lourde, allonge, à deux mains</p>',
	'<h3>Rapière</h3> 				<p>Arme de guerre de corps à corps (1 kg.)<br />Dégâts : 1d8 (perforant)<br />Finesse</p>',
	'<h3>Trident</h3> 				<p>Arme de guerre de corps à corps (2 kg.)<br />Dégâts : 1d6 (perforant)<br />Lancer (portée 6/18), versatile (1d8)</p>',

	'<h3>Arbalète de poing</h3>		<p>Arme de guerre à distance (1,5 kg.) <br />Dégâts : 1d6 (perforant)<br />Munition (portée 9/36), légère, chargement</p>',
	'<h3>Arbalète lourde</h3>  		<p>Arme de guerre à distance (9 kg.) <br />Dégâts : 1d10 (perforant)<br />Munition (portée 30/120), lourde, chargement, à deux mains</p>',
	'<h3>Arc long</h3> 				<p>Arme de guerre à distance (1 kg.) <br />Dégâts : 1d8 (perforant)<br />Munition (portée 45/180), lourde, à deux mains</p>',
	'<h3>Filet</h3> 				<p>Arme de guerre à distance (1,5 kg.) <br />Dégâts : -<br />Spécial, lancer (portée 1,50/4,50)</p>',
	'<h3>Sarbacane</h3> 			<p>Arme de guerre à distance (500 g.) <br />Dégâts : 1 (perforant)<br />Munition (portée 7,50/30), chargement</p>'
];

const AGEAPP = 'Âge apparent : ';
const ANS    = ' ans';